describe("vault-contract fixtures", function()
  it("loads the pinned contract manifest", function()
    local root = vim.env.MINIOBSIDIAN_ROOT or vim.fn.getcwd()
    local path = root .. "/tests/fixtures/vault-contract/v1/manifest.json"
    local manifest = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
    assert.equals("vault-contract/v1", manifest.contract)
    assert.equals(1, manifest.fixture_version)
    assert.is_true(#manifest.cases >= 9)
  end)
end)
